#!/bin/bash

if [ `/bin/arch` == "i686" ]
then
	echo rpm -Uvh $ROCKS_REBUILD_SRPM
	rpm -Uvh $ROCKS_REBUILD_SRPM

	export SPECFILE=kudzu.spec

	awk ' /^BuildPrereq: dietlibc/ { \
		next; \
	} \
	/^make RPM_OPT_FLAGS="%{optflags} -I." all kudzu/ { \
		printf("make DIET=\"\" "); \
		printf("RPM_OPT_FLAGS=\"\%{optflags} -I.\" all kudzu\n"); \
	} \
	{ print $0 } ' $REDHATSPECS/$SPECFILE > /tmp/$SPECFILE

	rpmbuild -bb /tmp/$SPECFILE

fi
