#!/opt/rocks/bin/python
#
# $Id: pre-10-src-install,v 1.12 2008/10/18 00:55:58 mjk Exp $
#
# @Copyright@
# 
# 				Rocks(r)
# 		         www.rocksclusters.org
# 		           version 5.1  (VI)
# 
# Copyright (c) 2000 - 2008 The Regents of the University of California.
# All rights reserved.	
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
# notice unmodified and in its entirety, this list of conditions and the
# following disclaimer in the documentation and/or other materials provided 
# with the distribution.
# 
# 3. All advertising and press materials, printed or electronic, mentioning
# features or use of this software must display the following acknowledgement: 
# 
# 	"This product includes software developed by the Rocks(r)
# 	Cluster Group at the San Diego Supercomputer Center at the
# 	University of California, San Diego and its contributors."
# 
# 4. Except as permitted for the purposes of acknowledgment in paragraph 3,
# neither the name or logo of this software nor the names of its
# authors may be used to endorse or promote products derived from this
# software without specific prior written permission.  The name of the
# software includes the following terms, and any derivatives thereof:
# "Rocks", "Rocks Clusters", and "Avalanche Installer".  For licensing of 
# the associated name, interested parties should contact Technology 
# Transfer & Intellectual Property Services, University of California, 
# San Diego, 9500 Gilman Drive, Mail Code 0910, La Jolla, CA 92093-0910, 
# Ph: (858) 534-5815, FAX: (858) 534-7345, E-MAIL:invent@ucsd.edu
# 
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# @Copyright@
#
# $Log: pre-10-src-install,v $
# Revision 1.12  2008/10/18 00:55:58  mjk
# copyright 5.1
#
# Revision 1.11  2008/03/06 23:41:41  mjk
# copyright storm on
#
# Revision 1.10  2007/06/23 04:03:21  mjk
# mars hill copyright
#
# Revision 1.9  2007/05/07 22:15:45  bruno
# ganglia restore rrds moved to ganglia roll
#
# Revision 1.8  2006/09/11 22:47:06  mjk
# monkey face copyright
#
# Revision 1.7  2006/08/10 00:09:29  mjk
# 4.2 copyright
#
# Revision 1.6  2006/01/16 06:48:57  mjk
# fix python path for source built foundation python
#
# Revision 1.5  2005/10/12 18:08:36  mjk
# final copyright for 4.1
#
# Revision 1.4  2005/09/16 01:02:15  mjk
# updated copyright
#
# Revision 1.3  2005/07/26 16:40:44  bruno
# change path to python found on rocks foundation
#
# Revision 1.2  2005/05/24 21:21:51  mjk
# update copyright, release is not any closer
#
# Revision 1.1  2005/03/01 02:02:45  mjk
# moved from core to base
#
# Revision 1.19  2004/03/25 03:15:31  bruno
# touch 'em all!
#
# update version numbers to 3.2.0 and update copyrights
#
# Revision 1.18  2003/10/15 22:19:46  bruno
# fixes for taroon
#
# Revision 1.17  2003/10/01 02:11:15  bruno
# fixes for anaconda 9
#
# Revision 1.16  2003/08/15 22:34:46  mjk
# 3.0.0 copyright
#
# Revision 1.15  2003/08/01 14:57:58  bruno
# fixes for redhat 9
#
# Revision 1.14  2003/05/22 16:39:27  mjk
# copyright
#
# Revision 1.13  2003/02/17 18:43:04  bruno
# updated copyright to 2003
#
# Revision 1.12  2002/11/14 20:38:55  mjk
# ia64 changes
#
# Revision 1.11  2002/11/05 18:12:02  bruno
# took out gm-devel test -- now that we downgraded to gm-1.5 this is
# no longer needed
#
# Revision 1.10  2002/10/23 00:27:38  bruno
# stop installing the gm-devel package
#
# Revision 1.9  2002/10/22 16:24:29  bruno
# cleanup
#
# Revision 1.8  2002/10/18 21:33:26  mjk
# Rocks 2.3 Copyright
#
# Revision 1.7  2002/10/12 00:45:24  bruno
# totally revamped this script.
#
# python is good.
#
# Revision 1.6  2002/10/12 00:25:37  bruno
# fixed path name to useradd
#
# moved SRPMS to /opt/rocks/SRPMS
#
# Revision 1.5  2002/10/03 14:41:40  bruno
# need to remove the source RPM after rebuilding or else we'll rebuild
# the RPM on every boot
#
# Revision 1.4  2002/05/01 13:27:27  bruno
# [ from singapore! ] leave the built rpm around
#
# Revision 1.3  2002/02/21 21:33:27  bruno
# added new copyright
#
# Revision 1.2  2001/05/09 20:17:13  bruno
# bumped copyright 2.1
#
# Revision 1.1  2001/05/08 21:09:35  bruno
# initial release
#
#

#
# look in the configuration source directory for source RPMS to build
#

import popen2
import string
import os
import shutil
import rocks.file

pkglist = []

try:
	filetree = rocks.file.Tree('/opt/rocks/SRPMS')
	for s in filetree.getFiles():
		if s.getPackageArch() != 'src':
			continue

		srpm = s.getFullName()
		print 'Building package: ', srpm

		cmd = 'rpmbuild --rebuild %s 2>&1 | tee /tmp/build.debug' % (srpm)
		stdout, stdin = popen2.popen2(cmd)

		for line in stdout.readlines():
			tokens = string.split(line)

			if len(tokens) >= 2 and tokens[0] == "Wrote:":
				pkglist.append(tokens[1])

		# move the source RPM from the rocks directory to the
		# redhat directory

		shutil.copy(srpm, '/usr/src/redhat/SRPMS')
		os.unlink(srpm)
except OSError:
	pass

#
# install each built package
#
for pkg in pkglist:
	print 'Installing package: ', pkg
	os.system('rpm -i --force %s' % (pkg))

#
# recompute the module dependancies
#
os.system('/sbin/depmod -a')

