#!/bin/bash
#
# This is not really a service. We simply publish several 411 files that rarely
# change. We do this to be symmetric to NIS (yp).
#
# chkconfig: 2345 27 15
# description: Publish various files via 411
#
# @Copyright@
# 
# 				Rocks(r)
# 		         www.rocksclusters.org
# 		         version 5.4 (Maverick)
# 
# Copyright (c) 2000 - 2010 The Regents of the University of California.
# All rights reserved.	
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
# notice unmodified and in its entirety, this list of conditions and the
# following disclaimer in the documentation and/or other materials provided 
# with the distribution.
# 
# 3. All advertising and press materials, printed or electronic, mentioning
# features or use of this software must display the following acknowledgement: 
# 
# 	"This product includes software developed by the Rocks(r)
# 	Cluster Group at the San Diego Supercomputer Center at the
# 	University of California, San Diego and its contributors."
# 
# 4. Except as permitted for the purposes of acknowledgment in paragraph 3,
# neither the name or logo of this software nor the names of its
# authors may be used to endorse or promote products derived from this
# software without specific prior written permission.  The name of the
# software includes the following terms, and any derivatives thereof:
# "Rocks", "Rocks Clusters", and "Avalanche Installer".  For licensing of 
# the associated name, interested parties should contact Technology 
# Transfer & Intellectual Property Services, University of California, 
# San Diego, 9500 Gilman Drive, Mail Code 0910, La Jolla, CA 92093-0910, 
# Ph: (858) 534-5815, FAX: (858) 534-7345, E-MAIL:invent@ucsd.edu
# 
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# @Copyright@
#
# $Log: 411,v $
# Revision 1.5  2010/09/07 23:52:48  bruno
# star power for gb
#
# Revision 1.4  2009/05/01 19:06:50  mjk
# chimi con queso
#
# Revision 1.3  2008/10/18 00:55:47  mjk
# copyright 5.1
#
# Revision 1.2  2008/03/06 23:41:32  mjk
# copyright storm on
#
# Revision 1.1  2007/12/10 21:28:34  bruno
# the base roll now contains several elements from the HPC roll, thus
# making the HPC roll optional.
#
# this also includes changes to help build and configure VMs for V.
#
# Revision 1.7  2007/06/23 04:03:39  mjk
# mars hill copyright
#
# Revision 1.6  2006/09/11 22:48:49  mjk
# monkey face copyright
#
# Revision 1.5  2006/08/10 00:10:54  mjk
# 4.2 copyright
#
# Revision 1.4  2005/10/12 18:09:43  mjk
# final copyright for 4.1
#
# Revision 1.3  2005/09/16 01:03:20  mjk
# updated copyright
#
# Revision 1.2  2005/05/24 21:22:45  mjk
# update copyright, release is not any closer
#
# Revision 1.1  2005/03/01 02:02:41  mjk
# moved from core to base
#
# Revision 1.1  2004/05/25 02:31:06  fds
# Since becoming a 411-master is a job that should not be taken on lightly, we
# are moving the tools necessary for it into a separate package. These files are
# essentially unchanged from those in 'rocks-411', except the initscript, which
# is slightly simpler.
#
# Revision 1.10  2004/04/02 03:31:31  fds
# Quieter on startup.
#
# Revision 1.9  2004/03/25 03:15:10  bruno
# touch 'em all!
#
# update version numbers to 3.2.0 and update copyrights
#
# Revision 1.8  2003/11/05 16:40:25  bruno
# moved 411 up to number 27 on startup -- needs to be before autofs
#
# Revision 1.7  2003/11/03 19:26:50  mjk
# moved rocksrc-lookup to bin (from sbin)
#
# Revision 1.6  2003/10/23 21:58:42  fds
# Added force makefile target and better reload
# action in init file. Allows us to easily resend all 411 alerts.
#
# Revision 1.5  2003/10/10 19:38:05  fds
# Respect to /opt/rocks/etc/rocksrc
#
# Revision 1.4  2003/08/15 22:34:46  mjk
# 3.0.0 copyright
#
# Revision 1.3  2003/08/13 19:06:38  fds
# Using makefile structure
#
# Revision 1.2  2003/08/11 17:26:17  fds
# Sending out alerts now so this service can be used as a "commit" for any
# changes to the /etc login files. Will put a bit more strain on the HTTP
# server at startup, but we have a backoff in the listener so lets use it.
#
# Commit facility is needed for passwd, groupadd cmd line tools that alter
# /etc login files but do not (yet) call 411put.
#
# Revision 1.1  2003/08/06 00:01:00  fds
# Moved 411 bootstrap service from rocks/config package.
#
# Revision 1.1  2003/08/05 23:50:18  fds
# A 411 bootstrap
#
#
#

# Source function library.
. /etc/rc.d/init.d/functions

makefile=/var/411/Makefile

case "$1" in
	start)
		echo -n "Publishing login files via 411..."

		make -C /var/411 > /dev/null 2>&1

		if [ $? -eq 0 ]; then
			success "411"
		else
			failure "411"
		fi

		echo
		;;

	stop)
		;;

	restart)
		# Force alerts to be resent.
		echo "Re-encrypting 411 files..."
		make -C /var/411 force > /dev/null 2>&1
		$0 stop
		$0 start
		;;
	status)
		echo "This service has no state."
		;;
	commit)
		echo "Commiting changes to login files using 411."
		echo
		
		# Like start, but more verbose.
		make -s -C /var/411

		;;
	*)
		echo "Usage: $NAME {start|stop|restart|status|commit}"
		exit 1
esac

exit 0
