#!/bin/sh
#
# $Id: rocks-kickstart,v 1.12 2012/11/27 00:48:39 phil Exp $
#
# chkconfig: 3 98 98
#
# description: set the node up for scalable kickstart installations
#
# this used to ensure the load on the frontend is capped when multiple
# nodes are asking for their kickstart files (i.e., asking for kickstart.cgi)
#
# @Copyright@
# 
# 				Rocks(r)
# 		         www.rocksclusters.org
# 		         version 6.2 (SideWindwer)
# 		         version 7.0 (Manzanita)
# 
# Copyright (c) 2000 - 2017 The Regents of the University of California.
# All rights reserved.	
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
# notice unmodified and in its entirety, this list of conditions and the
# following disclaimer in the documentation and/or other materials provided 
# with the distribution.
# 
# 3. All advertising and press materials, printed or electronic, mentioning
# features or use of this software must display the following acknowledgement: 
# 
# 	"This product includes software developed by the Rocks(r)
# 	Cluster Group at the San Diego Supercomputer Center at the
# 	University of California, San Diego and its contributors."
# 
# 4. Except as permitted for the purposes of acknowledgment in paragraph 3,
# neither the name or logo of this software nor the names of its
# authors may be used to endorse or promote products derived from this
# software without specific prior written permission.  The name of the
# software includes the following terms, and any derivatives thereof:
# "Rocks", "Rocks Clusters", and "Avalanche Installer".  For licensing of 
# the associated name, interested parties should contact Technology 
# Transfer & Intellectual Property Services, University of California, 
# San Diego, 9500 Gilman Drive, Mail Code 0910, La Jolla, CA 92093-0910, 
# Ph: (858) 534-5815, FAX: (858) 534-7345, E-MAIL:invent@ucsd.edu
# 
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# @Copyright@
#
# $Log: rocks-kickstart,v $
# Revision 1.12  2012/11/27 00:48:39  phil
# Copyright Storm for Emerald Boa
#
# Revision 1.11  2012/05/06 05:48:44  phil
# Copyright Storm for Mamba
#
# Revision 1.10  2011/07/23 02:30:47  phil
# Viper Copyright
#
# Revision 1.9  2010/09/07 23:53:07  bruno
# star power for gb
#
# Revision 1.8  2009/05/01 19:07:07  mjk
# chimi con queso
#
# Revision 1.7  2008/10/18 00:56:01  mjk
# copyright 5.1
#
# Revision 1.6  2008/03/06 23:41:43  mjk
# copyright storm on
#
# Revision 1.5  2007/06/23 04:03:23  mjk
# mars hill copyright
#
# Revision 1.4  2006/09/11 22:47:16  mjk
# monkey face copyright
#
# Revision 1.3  2006/08/10 00:09:38  mjk
# 4.2 copyright
#
# Revision 1.2  2005/10/12 18:08:40  mjk
# final copyright for 4.1
#
# Revision 1.1  2005/10/09 19:20:14  bruno
# change the kickstart.cgi load throttling code into a counting semaphore.
# initialize the semaphore to the number of CPUs on the frontend multiplied by 2.
# as the number of CPUs on the frontend increases, we'll be able to support
# more concurrent executions of kpp.
#
# also, create an init script that removes the kickstart.cgi.lck file every
# time the service is started/stopped. this ensures a frontend reboot will
# reset the state of the throttling code.
#
#
#
. /etc/rc.d/init.d/functions

LOCKFILE=/var/tmp/kickstart.cgi.lck

start() {
	action "Rocks Kickstart: " true
	rm -f $LOCKFILE
}

stop() {
	action "Rocks Kickstart: " true
	rm -f $LOCKFILE
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	RETVAL=1	
esac

exit $RETVAL

